///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String darkmodeMoon = 'assets/image/darkmode/moon.png';
  static const String darkmodeSun = 'assets/image/darkmode/sun.png';
  static const String flagFlagKr = 'assets/image/flag/flag_kr.png';
  static const String flagFlagUs = 'assets/image/flag/flag_us.png';
  static const String iconDeleteX = 'assets/image/icon/delete_x.svg';
  static const String imageSmallArrowRight =
      'assets/image/small_arrow_right.svg';
  static const String jsonLicenses = 'assets/json/licenses.json';
  static const String riveFireButton = 'assets/rive/fire-button.riv';
  static const String translationsEn = 'assets/translations/en.json';
  static const String translationsKo = 'assets/translations/ko.json';
}
